import { writable } from 'svelte/store';

const CHAR_PRESETS = [
  { name: 'Classic',  chars: ' .:-=+*#%@' },
  { name: 'Detailed', chars: ' .,:;+*?%#@' },
  { name: 'Numbers',  chars: ' 0123456789' },
  { name: 'Blocks',   chars: ' ░▒▓█' },
  { name: 'Binary',   chars: ' 01' },
  { name: 'Braille',  chars: ' \u2801\u2802\u2804\u2840\u2880\u28C0\u28E4\u28F6\u28FF' },
  { name: 'Minimal',  chars: ' ·:+' },
];

const defaults = {
  chars: CHAR_PRESETS[0].chars,
  fontSize: 10,
  saturationBoost: 1.4,
  brightnessBoost: 1.3,
  lineHeight: 1.0,
  colored: true,
  mix: 1.0,
  blendMode: 'normal',
  tileSize: 1,
  posterize: 32,
  hoverRadius: 8,
  hoverExposure: 0.35,
  hoverEnabled: false,
  basicHover: false,
  canvasColor: { r: 0, g: 0, b: 0 },
  asciiColorOverride: false,
  asciiColor: { r: 255, g: 255, b: 255 },
  sourceScale: 0.65,
  sourceOffsetX: 0,
  sourceOffsetY: 0,
  sourceOpacity: 1.0,
  asciiOpacity: 1.0,
  sourceVisible: true,
  asciiVisible: true,
  effectIntensity: 100,
  videoMode: false,
  animEnabled: false,
  animType: 'default',
  animSpeed: 50,
  animAmplitude: 30,
  revealActive: false,
  revealDirection: 'center-out',
  revealFocalX: 50,
  revealFocalY: 50,
  revealSpeed: 35,
  revealGradient: 0,
  revealColor1: '#ffffff',
  revealColor2: '#ff3333',
  revealColor3: '#ffffff',
  revealProgress: 0,
  revealColorProgress: 0,
  revealStartTime: 0,
  gooeyHover: false,
  gooeyScrambleSeed: 0,
  gooeyIntensity: 0,
  gooeyRadius: 8,
  gooeySoftness: 50,
  gooeyScrambleAmt: 100,
  gooeyColorReveal: 100,
  glowTrail: true,
  glowPoints: [],
  glowRadiusMult: 8,
  glowDuration: 1.0,
  glowIntensity: 2.5,
  glowStampInterval: 25,
  glowLastStamp: 0,
  hdrEnabled: false,
  hdrBloom: 60,
  hdrBloomRadius: 12,
  hdrBloomThreshold: 40,
  hdrIntensity: 150,
  hdrShadowLift: 20,
  frameWidth: 800,
  frameHeight: 600,
  useCustomFrame: false,
};

export { CHAR_PRESETS, defaults };
export const config = writable({ ...defaults });

export function batchUpdateConfig(partial) {
  config.update(c => ({ ...c, ...partial }));
}

